name: Daily Job at 5 PM IST

on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'  # 5:00 PM IST

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "Running at 5:00 PM IST"
