name: Run Exchange Rate Script

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * *' # Every day at 3 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SQL_USER: ${{ secrets.env.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.env.SQL_PASSWORD }}
      SQL_SERVER: ${{ secrets.env.SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.env.SQL_DATABASE }} 
      SQL_PORT: ${{ secrets.env.SQL_PORT }}
      # BITRIX_URL: ${{ secrets.env.BITRIX_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install only Chromium
        run: npx playwright install chromium

      - name: Run Playwright test (Chromium only)
        run: npx playwright test tests/exchangerates.spec.js
